### ISSUE TITLE
'PosTagVisualizer' object has no attribute 'tagged'

### ISSUE THREAD

**Issue by AolingHmlet** [foxbook/atap#103]
Hi When I tried to copy the code in CH8 to visualise pos_tag. It gave me the below error:

'PosTagVisualizer' object has no attribute 'tagged' and also it shows 'PosTagVisualizer' object has no attribute 'colorize'

Can anyone help? Thanks a lot.

**Comment by bbengfort** [comment]
Hi @AolingHmlet - thanks for checking out the Fox book! 

The Visualizer in Yellowbrick has changed in the v1.0 release and doesn't have the same API. The simplest way to use it is to parse raw text directly as follows:

```python
from yellowbrick.text import PosTagVisualizer

pie = """
    In a small saucepan, combine sugar and eggs
    until well blended. Cook over low heat, stirring
    constantly, until mixture reaches 160° and coats
    the back of a metal spoon. Remove from the heat.
    Stir in chocolate and vanilla until smooth. Cool
    to lukewarm (90°), stirring occasionally. In a small
    bowl, cream butter until light and fluffy. Add cooled
    chocolate mixture; beat on high speed for 5 minutes
    or until light and fluffy. In another large bowl,
    beat cream until it begins to thicken. Add
    confectioners' sugar; beat until stiff peaks form.
    Fold into chocolate mixture. Pour into crust. Chill
    for at least 6 hours before serving. Garnish with
    whipped cream and chocolate curls if desired.
    """

visualizer = PosTagVisualizer(parser='nltk')
visualizer.fit_transform([pie])
visualizer.show()
```

![figure1](https://user-images.githubusercontent.com/745966/103246924-176b4d80-4933-11eb-9947-3e5b4e067f27.png)


Of course, since you're reading the Fox book - you probably want to apply your own text analysis tools, and you can do that by passing a list of documents which are lists of sentences, which are lists of (term, tag) tuples as follows:


```python
from nltk import pos_tag, sent_tokenize, word_tokenize
from yellowbrick.text import PosTagVisualizer

nursery_rhyme = """
    Baa, baa, black sheep,
    Have you any wool?
    Yes, sir, yes, sir,
    Three bags full;
    One for the master,
    And one for the dame,
    And one for the little boy
    Who lives down the lane.
    """


def preprocess(text):
    for sent in sent_tokenize(text):
        yield pos_tag(word_tokenize(sent))


tagged = preprocess(nursery_rhyme)

visualizer = PosTagVisualizer()
visualizer.fit([list(tagged)])
visualizer.show()
```

![figure2](https://user-images.githubusercontent.com/745966/103247024-70d37c80-4933-11eb-90c6-b2294232e090.png)


Please note the braces in the `visualizer.fit([list(tagged)])` signature - the `fit()` method expects a list of documents, and since you only have one document to visualize, you'll need to pass it a list of the single tagged document.
