### ISSUE TITLE
New sample of Baleen Corpus

### ISSUE THREAD

**Issue by bbengfort** [foxbook/atap#19]
Specifically for Chapter 8 - run a new sample of the corpus that is a bit smaller (so centrality actually computes) and whose key phrases are a bit better.

**Comment by rebeccabilbro** [comment]
In the DDL data lake bucket, there's a folder called something like Baleen 20170320 - march 20 of this year. If we want to do a new dump:

1.  It will be 524 gigs uncompressed - too big for any of our machines! Options: stand up an AWS instance or buy a terabyte hard drive. @ojedatony1616 will order the external hard drive.

2. Use AWS to download `.tar` to external hard drive (put it into \volumes - make sure not crossing your hard drive first). Do it from command line rather than web interface! 

3. Decompress. 

4. Then use minke for `sample` command. Provide a source path and a target path. Specify the percent (default is 10% - stick with this). Should give an even distribution by category. Should take 1 hour (if more let @bbengfort know)

5. zip new sample and stick on S3

6. Pass that download link to reviewers and co-authors

**Comment by rebeccabilbro** [comment]
See https://github.com/DistrictDataLabs/baleen/issues/91#issuecomment-306925401
